services:
  postgres:
    image: postgres:16
    container_name: iot_postgres
    environment:
      POSTGRES_DB: iot_platform
      POSTGRES_USER: iot_user
      POSTGRES_PASSWORD: iot_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: iot_mosquitto
    ports:
      - "1883:1883"

  flask_app:
    build: .
    container_name: iot_flask_app
    command: python3 -u app.py
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - mosquitto

  gateway_offline_worker:
    build: .
    container_name: iot_gateway_offline_worker
    command: python3 -u gateway_offline_worker.py
    depends_on:
      - postgres




  mqtt_subscriber:
    build: .
    container_name: iot_mqtt_subscriber
    command: python3 -u mqtt_subscriber.py
    depends_on:
      - postgres
      - mosquitto

  mqtt_device_simulator:
    build: .
    container_name: iot_mqtt_device_simulator
    command: python3 -u mqtt_device_simulator.py
    depends_on:
      - mosquitto



  fastapi_server:
    build: .
    container_name: iot_fastapi_server
    command: uvicorn fastapi_server:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - mosquitto

  heartbeat_worker:
    build: .
    container_name: iot_heartbeat_worker
    command: python3 -u heartbeat_worker.py
    depends_on:
      - postgres
      - mosquitto



  gateway_simulator:
    build: .
    container_name: iot_gateway_simulator
    command: python3 -u gateway_simulator.py
    depends_on:
      - mosquitto

  gateway_command_worker:
    build: .
    container_name: iot_gateway_command_worker
    command: python3 -u gateway_command_worker.py
    depends_on:
      - postgres
  
  iot_device_command_worker:
    build: .
    container_name: iot_device_command_worker
    command: python3 -u iot_device_command_worker.py
    depends_on:
      - postgres


  iot_firmware_update_worker:
    build: .
    container_name: iot_firmware_update_worker
    command: python3 -u iot_firmware_update_worker.py
    depends_on:
      - postgres

volumes:
  postgres_data:



